[package]
name = "valsoray-dev"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = { version = "4.4", default-features = false, features = ["macros"] }
dotenv = "0.15"
log = "0.4.20"
pretty_env_logger = "0.5.0"
