[package]
name = "valsoray-dev"
version = "1.1.0"
edition = "2021"

[[bin]]
name = "valsoray-dev"
path = "src/main.rs"

[dependencies]
actix-files = "0.6"
actix-web = { version = "4.4", default-features = false, features = ["macros"] }
dotenvy = "0.15"
log = "0.4.20"
pretty_env_logger = "0.5.0"
